[
    {
        "additional_details": null,
        "exception": "Failed to call fetch_all() for resource snapshots: 'Snapshot' object has no attribute 'hyper_vgeneration'",
        "file": "base.py",
        "line": 17,
        "traceback": "Traceback (most recent call last):\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/base/resources/base.py\", line 17, in call\n    await task\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/snapshots.py\", line 14, in fetch_all\n    id, snapshot = self._parse_snapshot(raw_snapshot)\n                   ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/snapshots.py\", line 30, in _parse_snapshot\n    snapshot_dict['hyper_vgeneration'] = raw_snapshot.hyper_vgeneration\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Snapshot' object has no attribute 'hyper_vgeneration'. Did you mean: 'hyper_v_generation'?\n"
    },
    {
        "additional_details": null,
        "exception": "Failed to call fetch_all() for resource snapshots: 'Snapshot' object has no attribute 'hyper_vgeneration'",
        "file": "base.py",
        "line": 17,
        "traceback": "Traceback (most recent call last):\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/base/resources/base.py\", line 17, in call\n    await task\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/snapshots.py\", line 14, in fetch_all\n    id, snapshot = self._parse_snapshot(raw_snapshot)\n                   ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/snapshots.py\", line 30, in _parse_snapshot\n    snapshot_dict['hyper_vgeneration'] = raw_snapshot.hyper_vgeneration\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Snapshot' object has no attribute 'hyper_vgeneration'. Did you mean: 'hyper_v_generation'?\n"
    },
    {
        "additional_details": null,
        "exception": "Failed to call fetch_all() for resource images: 'Image' object has no attribute 'hyper_vgeneration'",
        "file": "base.py",
        "line": 17,
        "traceback": "Traceback (most recent call last):\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/base/resources/base.py\", line 17, in call\n    await task\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/images.py\", line 14, in fetch_all\n    id, image = self._parse_image(raw_image)\n                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/images.py\", line 27, in _parse_image\n    image_dict['hyper_vgeneration'] = raw_image.hyper_vgeneration\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Image' object has no attribute 'hyper_vgeneration'. Did you mean: 'hyper_v_generation'?\n"
    },
    {
        "additional_details": null,
        "exception": "Failed to retrieve blob containers: (FeatureNotSupportedForAccount) Blob is not supported for the account.\nCode: FeatureNotSupportedForAccount\nMessage: Blob is not supported for the account.",
        "file": "storageaccounts.py",
        "line": 38,
        "traceback": "Traceback (most recent call last):\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py\", line 38, in get_blob_containers\n    containers = await run_concurrently(\n                 ^^^^^^^^^^^^^^^^^^^^^^^\n        lambda: list(client.blob_containers.list(resource_group_name, storage_account_name))\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/utils.py\", line 27, in run_concurrently\n    return await run_function_concurrently(function)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.13/concurrent/futures/thread.py\", line 59, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py\", line 39, in <lambda>\n    lambda: list(client.blob_containers.list(resource_group_name, storage_account_name))\n            ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/core/paging.py\", line 136, in __next__\n    return next(self._page_iterator)\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/core/paging.py\", line 82, in __next__\n    self._response = self._get_next(self.continuation_token)\n                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/mgmt/storage/v2021_01_01/operations/_blob_containers_operations.py\", line 135, in get_next\n    raise HttpResponseError(response=response, error_format=ARMErrorFormat)\nazure.core.exceptions.HttpResponseError: (FeatureNotSupportedForAccount) Blob is not supported for the account.\nCode: FeatureNotSupportedForAccount\nMessage: Blob is not supported for the account.\n"
    },
    {
        "additional_details": null,
        "exception": "Failed to retrieve blob services: (FeatureNotSupportedForAccount) Blob is not supported for the account.\nCode: FeatureNotSupportedForAccount\nMessage: Blob is not supported for the account.",
        "file": "storageaccounts.py",
        "line": 51,
        "traceback": "Traceback (most recent call last):\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py\", line 51, in get_blob_services\n    blob_services = await run_concurrently(\n                    ^^^^^^^^^^^^^^^^^^^^^^^\n        lambda: list(client.blob_services.list(resource_group_name, storage_account_name))\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/utils.py\", line 27, in run_concurrently\n    return await run_function_concurrently(function)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.13/concurrent/futures/thread.py\", line 59, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py\", line 52, in <lambda>\n    lambda: list(client.blob_services.list(resource_group_name, storage_account_name))\n            ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/core/paging.py\", line 136, in __next__\n    return next(self._page_iterator)\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/core/paging.py\", line 82, in __next__\n    self._response = self._get_next(self.continuation_token)\n                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/mgmt/storage/v2021_01_01/operations/_blob_services_operations.py\", line 117, in get_next\n    raise HttpResponseError(response=response, error_format=ARMErrorFormat)\nazure.core.exceptions.HttpResponseError: (FeatureNotSupportedForAccount) Blob is not supported for the account.\nCode: FeatureNotSupportedForAccount\nMessage: Blob is not supported for the account.\n"
    },
    {
        "additional_details": null,
        "exception": "Failed to retrieve blob services: (FeatureNotSupportedForAccount) Blob is not supported for the account.\nCode: FeatureNotSupportedForAccount\nMessage: Blob is not supported for the account.",
        "file": "storageaccounts.py",
        "line": 51,
        "traceback": "Traceback (most recent call last):\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py\", line 51, in get_blob_services\n    blob_services = await run_concurrently(\n                    ^^^^^^^^^^^^^^^^^^^^^^^\n        lambda: list(client.blob_services.list(resource_group_name, storage_account_name))\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/utils.py\", line 27, in run_concurrently\n    return await run_function_concurrently(function)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.13/concurrent/futures/thread.py\", line 59, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py\", line 52, in <lambda>\n    lambda: list(client.blob_services.list(resource_group_name, storage_account_name))\n            ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/core/paging.py\", line 136, in __next__\n    return next(self._page_iterator)\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/core/paging.py\", line 82, in __next__\n    self._response = self._get_next(self.continuation_token)\n                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/mgmt/storage/v2021_01_01/operations/_blob_services_operations.py\", line 117, in get_next\n    raise HttpResponseError(response=response, error_format=ARMErrorFormat)\nazure.core.exceptions.HttpResponseError: (FeatureNotSupportedForAccount) Blob is not supported for the account.\nCode: FeatureNotSupportedForAccount\nMessage: Blob is not supported for the account.\n"
    },
    {
        "additional_details": null,
        "exception": "Failed to retrieve blob containers: (FeatureNotSupportedForAccount) Blob is not supported for the account.\nCode: FeatureNotSupportedForAccount\nMessage: Blob is not supported for the account.",
        "file": "storageaccounts.py",
        "line": 38,
        "traceback": "Traceback (most recent call last):\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py\", line 38, in get_blob_containers\n    containers = await run_concurrently(\n                 ^^^^^^^^^^^^^^^^^^^^^^^\n        lambda: list(client.blob_containers.list(resource_group_name, storage_account_name))\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/utils.py\", line 27, in run_concurrently\n    return await run_function_concurrently(function)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.13/concurrent/futures/thread.py\", line 59, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py\", line 39, in <lambda>\n    lambda: list(client.blob_containers.list(resource_group_name, storage_account_name))\n            ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/core/paging.py\", line 136, in __next__\n    return next(self._page_iterator)\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/core/paging.py\", line 82, in __next__\n    self._response = self._get_next(self.continuation_token)\n                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/mgmt/storage/v2021_01_01/operations/_blob_containers_operations.py\", line 135, in get_next\n    raise HttpResponseError(response=response, error_format=ARMErrorFormat)\nazure.core.exceptions.HttpResponseError: (FeatureNotSupportedForAccount) Blob is not supported for the account.\nCode: FeatureNotSupportedForAccount\nMessage: Blob is not supported for the account.\n"
    },
    {
        "additional_details": null,
        "exception": "Failed to retrieve blob containers: (FeatureNotSupportedForAccount) Blob is not supported for the account.\nCode: FeatureNotSupportedForAccount\nMessage: Blob is not supported for the account.",
        "file": "storageaccounts.py",
        "line": 38,
        "traceback": "Traceback (most recent call last):\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py\", line 38, in get_blob_containers\n    containers = await run_concurrently(\n                 ^^^^^^^^^^^^^^^^^^^^^^^\n        lambda: list(client.blob_containers.list(resource_group_name, storage_account_name))\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/utils.py\", line 27, in run_concurrently\n    return await run_function_concurrently(function)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.13/concurrent/futures/thread.py\", line 59, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py\", line 39, in <lambda>\n    lambda: list(client.blob_containers.list(resource_group_name, storage_account_name))\n            ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/core/paging.py\", line 136, in __next__\n    return next(self._page_iterator)\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/core/paging.py\", line 82, in __next__\n    self._response = self._get_next(self.continuation_token)\n                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/mgmt/storage/v2021_01_01/operations/_blob_containers_operations.py\", line 135, in get_next\n    raise HttpResponseError(response=response, error_format=ARMErrorFormat)\nazure.core.exceptions.HttpResponseError: (FeatureNotSupportedForAccount) Blob is not supported for the account.\nCode: FeatureNotSupportedForAccount\nMessage: Blob is not supported for the account.\n"
    },
    {
        "additional_details": null,
        "exception": "Failed to retrieve blob services: (FeatureNotSupportedForAccount) Blob is not supported for the account.\nCode: FeatureNotSupportedForAccount\nMessage: Blob is not supported for the account.",
        "file": "storageaccounts.py",
        "line": 51,
        "traceback": "Traceback (most recent call last):\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py\", line 51, in get_blob_services\n    blob_services = await run_concurrently(\n                    ^^^^^^^^^^^^^^^^^^^^^^^\n        lambda: list(client.blob_services.list(resource_group_name, storage_account_name))\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/utils.py\", line 27, in run_concurrently\n    return await run_function_concurrently(function)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.13/concurrent/futures/thread.py\", line 59, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py\", line 52, in <lambda>\n    lambda: list(client.blob_services.list(resource_group_name, storage_account_name))\n            ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/core/paging.py\", line 136, in __next__\n    return next(self._page_iterator)\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/core/paging.py\", line 82, in __next__\n    self._response = self._get_next(self.continuation_token)\n                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/venv/lib/python3.13/site-packages/azure/mgmt/storage/v2021_01_01/operations/_blob_services_operations.py\", line 117, in get_next\n    raise HttpResponseError(response=response, error_format=ARMErrorFormat)\nazure.core.exceptions.HttpResponseError: (FeatureNotSupportedForAccount) Blob is not supported for the account.\nCode: FeatureNotSupportedForAccount\nMessage: Blob is not supported for the account.\n"
    },
    {
        "additional_details": null,
        "exception": "Failed to call fetch_all() for resource instances: 'NoneType' object has no attribute 'version'",
        "file": "base.py",
        "line": 17,
        "traceback": "Traceback (most recent call last):\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/base/resources/base.py\", line 17, in call\n    await task\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/instances.py\", line 16, in fetch_all\n    id, instance = await self._parse_instance(raw_instance)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/instances.py\", line 92, in _parse_instance\n    instance_dict['storage_profile']['Release'] = raw_instance.storage_profile.image_reference.version\n                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'version'\n"
    },
    {
        "additional_details": null,
        "exception": "Failed to call fetch_all() for resource instances: 'NoneType' object has no attribute 'version'",
        "file": "base.py",
        "line": 17,
        "traceback": "Traceback (most recent call last):\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/base/resources/base.py\", line 17, in call\n    await task\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/instances.py\", line 16, in fetch_all\n    id, instance = await self._parse_instance(raw_instance)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/kronos/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/instances.py\", line 92, in _parse_instance\n    instance_dict['storage_profile']['Release'] = raw_instance.storage_profile.image_reference.version\n                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'version'\n"
    }
]
